export const allProjects = [
  {
    title: "Nerdwork",
    desc: "Nerdwork is the home for fans: a creative entertainment studio & thriving community best known for its annual Comic-Con. They are the intersection of storytelling, tech, culture, and fandom.",
    tags: ["Next.js", "Typescript", "Tanstack Query"],
    image: "/portfolio/nerdwork-port.png",
    live: "https://www.nerdworkng.com//",
    github: "#",
  },
  {
    title: "Resolve.vote",
    desc: "A transparent voting system designed for community governance and decision resolution.",
    tags: ["Next.js", "Typescript", "Tanstack Query"],
    image: "/portfolio/resolve-port.png",
    live: "https://resolve.vote/",
    github: "#",
  },
  {
    title: "Audiophile",
    desc: "A premium e-commerce experience for high-fidelity audio equipment, featuring a seamless cart system.",
    tags: ["Next.js", "Convex", "Typescript", "Framer Motion"],
    image: "/portfolio/audiophile-port.png",
    live: "https://audiophile-five-hazel.vercel.app/",
    github: "https://github.com/ayomikun-ade/audiophile",
  },
  {
    title: "Valentine Verses",
    desc: "An AI-powered poetry generator leveraging Groq Cloud for instant, personalized romantic verses.",
    tags: ["React", "Framer", "Groq Cloud", "FastAPI"],
    image: "/portfolio/valentine-port.png",
    live: "https://valentine-verses.vercel.app/",
    github: "https://github.com/ayomikun-ade/valentineverses.ui",
  },
  {
    title: "Aurela",
    desc: "A visually immersive landing page for a skin care agency, utilizing advanced motion primitives.",
    tags: ["Next.js", "Framer Motion"],
    live: "https://aurela.pxxl.click/",
    github: "https://github.com/ayomikun-ade/aurela",
    image: "/portfolio/aurela-port.png   ",
  },
  {
    title: "FixFlow",
    desc: "A streamlined issue tracking application for property management with real-time status updates.",
    tags: ["Nextjs", "Convex", "Clerk", "Typescript"],
    live: "https://fix-flow-react.vercel.app/",
    github: "https://github.com/ayomikun-ade/fix-flow-react",
    image: "/portfolio/fixflow-port.png",
  },
];
